name: Automated dev builds

on:
  workflow_dispatch:
  push:
    branches:
      - 'trunk'
      - 'ver/**'
      - 'feat/**'

jobs:
  fabric:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Data Generation
        run: ./gradlew runDatagen
        continue-on-error: true

      - name: Build
        run: ./gradlew build

      - name: Publish artifacts
        uses: DrTheodor/discord-webhook-upload-action@v1.2
        with:
          url: ${{ secrets.DEV_BUILDS }}
          file: 'build/libs/*'
          username: igor
          avatar: 'https://static.wikia.nocookie.net/megamitensei/images/9/9a/IgorPersona3.png/revision/latest/scale-to-width/360?cb=20141103082542'
          commit: '> :sparkles: [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>)'
          message: |
            <:new1:1253371736510959636><:new2:1253371805734015006> New `${{ github.repository }}` dev build `#${{ github.run_number }}`:
            %COMMITS%
